#!/bin/bash
set -e
f(){
  mkdir -p $DIR
#  m
  s
}

m(){

  if [ -s $DIR/usage.json ] && [ ! -s $DIR/meta.json ]; then
    curl -s -S -L \
     -H "Accept: application/vnd.github+json" \
     -H "Authorization: Bearer $GITHUB_TOKEN"\
     -H "X-GitHub-Api-Version: 2022-11-28" \
     -o $DIR/meta.json \
     "https://api.github.com/repos/$ORG/$REPO/actions/runs/$RUN"
    sleep 1
  fi

}

s(){

  if [ ! -s $DIR/usage.json ] && [ -s $DIR/meta.json ]; then
    curl -s -S -L \
     -H "Accept: application/vnd.github+json" \
     -H "Authorization: Bearer $GITHUB_TOKEN"\
     -H "X-GitHub-Api-Version: 2022-11-28" \
     -o $DIR/usage.json \
     "https://api.github.com/repos/$ORG/$REPO/actions/runs/$RUN/timing"
    echo -n s
  fi
  if [  -s $DIR/usage.json ] ;then
    echo -n .
    jq . < $DIR/meta.json > .$$ && mv .$$ $DIR/meta.json
    jq . < $DIR/usage.json > .$$ && mv .$$ $DIR/usage.json
  fi
}

if (($# < 3)); then
  echo usage: $0 ORG REPO RUN
else
  export ORG=$1
  export REPO=$2
  export RUN=$3
  export DIR=$1/$2/$3
  f $ORG $REPO $RUN
fi

