#!/bin/bash
set -e
s(){
  DIR=$ORG/$REPO/$RUN
  mkdir -p $DIR

  if [ -s $DIR/usage.json ] && [ ! -s $DIR/meta.json ]; then
    curl -s -S -L \
     -H "Accept: application/vnd.github+json" \
     -H "Authorization: Bearer $GITHUB_TOKEN"\
     -H "X-GitHub-Api-Version: 2022-11-28" \
     -o $DIR/meta.json \
     "https://api.github.com/repos/$ORG/$REPO/actions/runs/$RUN"
    sleep 1
  fi
  echo $ORG $REPO $RUN

}


if (($# < 3)); then
  echo usage: $0 ORG REPO RUN
else
  export ORG=$1
  export REPO=$2
  export RUN=$3
  s $ORG $REPO $RUN
fi
